# fly.toml app configuration file generated for n-ring on 2023-12-31T07:04:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "n-ring"
primary_region = "nrt"

[build]

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
