#"tag" ,  "short",  "  long  ",  "  ja_jp  "
#" 0 " ,  "  1  ",  "   2    ",  "    3    "
sp3_temp = [
  ["main", "m_sho", "main_sho", "シューター"],
  ["main", "m_rol", "main_rol", "ローラー"],
  ["main", "m_cha", "main_cha", "チャージャー"],
  ["main", "m_spi", "main_spi", "スピナー"],
  ["main", "m_bla", "main_bla", "ブラスター"],
  ["main", "m_hud", "main_hud", "フデ"],
  ["main", "m_thr", "main_thr", "スロッシャー"],
  ["main", "m_she", "main_she", "シェルター"],
  ["main", "m_wip", "main_wip", "ワイパー"],
  ["main", "m_man", "main_man", "マニューバー"],
  ["main", "m_str", "main_str", "ストリンガー"],
  ["sub", "s_spb", "sub_spb", "スプラッシュボム"],
  ["sub", "s_kbb", "sub_kbb", "キューバンボム"],
  ["sub", "s_qkb", "sub_qkb", "クイックボム"],
  ["sub", "s_srk", "sub_srk", "スプリンクラー"],
  ["sub", "s_shi", "sub_shi", "スプラッシュシールド"],
  ["sub", "s_tsb", "sub_tsb", "タンサンボム"],
  ["sub", "s_crb", "sub_crb", "カーリングボム"],
  ["sub", "s_rbb", "sub_rbb", "ロボットボム"],
  ["sub", "s_bea", "sub_bea", "ジャンプビーコン"],
  ["sub", "s_sen", "sub_sen", "ポイントセンサー"],
  ["sub", "s_tra", "sub_tra", "トラップ"],
  ["sub", "s_poi", "sub_poi", "ポイズンミスト"],
  ["sub", "s_tpd", "sub_tpd", "トーピード"],
  ["sub", "s_lmk", "sub_lmk", "ラインマーカー"],
  ["sp", "p_uts", "sp_uts", "ウルトラショット"],
  ["sp", "p_grb", "sp_grb", "グレートバリア"],
  ["sp", "p_swd", "sp_swd", "ショクワンダー"],
  ["sp", "p_hps", "sp_hps", "ホップソナー"],
  ["sp", "p_kik", "sp_kik", "キューインキ"],
  ["sp", "p_mgl", "sp_mgl", "メガホンレーザー5.1ch"],
  ["sp", "p_knt", "sp_knt", "カニタンク"],
  ["sp", "p_smr", "sp_smr", "サメライド"],
  ["sp", "p_trt", "sp_trt", "トリプルトルネード"],
  ["sp", "p_ens", "sp_ens", "エナジースタンド"],
  ["sp", "p_toi", "sp_toi", "テイオウイカ"],
  ["sp", "p_dct", "sp_dct", "デコイチラシ"],
  ["sp", "p_mtm", "sp_mtm", "マルチミサイル"],
  ["sp", "p_ncd", "sp_ncd", "ナイスダマ"],
  ["sp", "p_jtp", "sp_jtp", "ジェットパック"],
  ["sp", "p_uth", "sp_uth", "ウルトラハンコ"],
  ["sp", "p_smn", "sp_smn", "スミナガシート"]
]
