map = [
  #1.0.0
  [
    "ユノハナ大渓谷",
    "https://cdn.wikimg.net/en/splatoonwiki/images/1/1c/S3_Stage_Scorch_Gorge.png"
  ],
  [
    "ゴンズイ地区",
    "https://cdn.wikimg.net/en/splatoonwiki/images/7/7d/S3_Stage_Eeltail_Alley.png"
  ],
  [
    "キンメダイ美術館",
    "https://cdn.wikimg.net/en/splatoonwiki/images/6/6a/S3_Stage_Museum_d%27Alfonsino.png"
  ],
  [
    "マテガイ放水路",
    "https://cdn.wikimg.net/en/splatoonwiki/images/a/ad/S3_Stage_Undertow_Spillway.png"
  ],
  [
    "ナメロウ金属",
    "https://cdn.wikimg.net/en/splatoonwiki/images/d/d1/S3_Stage_Mincemeat_Metalworks.png"
  ],
  [
    "ヤガラ市場",
    "https://cdn.wikimg.net/en/splatoonwiki/images/a/ad/S3_Stage_Hagglefish_Market.png"
  ],
  [
    "マサバ海峡大橋",
    "https://cdn.wikimg.net/en/splatoonwiki/images/9/94/S3_Stage_Hammerhead_Bridge.png"
  ],
  [
    "マヒマヒリゾート&スパ",
    "https://cdn.wikimg.net/en/splatoonwiki/images/archive/6/6b/20230225034609%21S3_Stage_Mahi-Mahi_Resort.png"
  ],
  [
    "海女美術大学",
    "https://cdn.wikimg.net/en/splatoonwiki/images/4/45/S3_Stage_Inkblot_Art_Academy.png"
  ],
  [
    "チョウザメ造船",
    "https://cdn.wikimg.net/en/splatoonwiki/images/4/45/S3_Stage_Sturgeon_Shipyard.png"
  ],
  [
    "ザトウマーケット",
    "https://cdn.wikimg.net/en/splatoonwiki/images/4/47/S3_Stage_MakoMart.png"
  ],
  [
    "スメーシーワールド",
    "https://cdn.wikimg.net/en/splatoonwiki/images/7/71/S3_Stage_Wahoo_World.png"
  ],
  ## 2.0.0
  [
    "クサヤ温泉",
    "https://cdn.wikimg.net/en/splatoonwiki/images/f/fc/S3_Stage_Brinewater_Springs.png"
  ],
  [
    "ヒラメが丘団地",
    "https://cdn.wikimg.net/en/splatoonwiki/images/2/23/S3_Stage_Flounder_Heights.png"
  ],
  ## 3.0.0
  [
    "ナンプラー遺跡",
    "https://cdn.wikimg.net/en/splatoonwiki/images/9/95/S3_Stage_Um%27ami_Ruins.png"
  ],
  [
    "マンタマリア号",
    "https://cdn.wikimg.net/en/splatoonwiki/images/8/86/S3_Stage_Manta_Maria.png"
  ],
  ## 4.0.0
  [
    "タラポートショッピングパーク",
    "https://cdn.wikimg.net/en/splatoonwiki/images/2/2a/S3_Stage_Barnacle_%26_Dime.png"
  ],
  [
    "コンブトラック",
    "https://cdn.wikimg.net/en/splatoonwiki/images/5/57/S3_Stage_Humpback_Pump_Track.png"
  ],
  ## 5.0.0
  [
    "タカアシ経済特区",
    "https://cdn.wikimg.net/en/splatoonwiki/images/b/bb/S3_Stage_Crableg_Capital.png"
  ],
  [
    "オヒョウ海運",
    "https://cdn.wikimg.net/en/splatoonwiki/images/8/8b/S3_Stage_Shipshape_Cargo_Co..png"
  ],
  ## 6.0.0
  [
    "バイガイ亭",
    "https://cdn.wikimg.net/en/splatoonwiki/images/9/92/S3_Stage_Robo_ROM-en.png"
  ],
  [
    "ネギトロ炭鉱",
    "https://cdn.wikimg.net/en/splatoonwiki/images/6/69/S3_Stage_Bluefin_Depot.png"
  ],
  ## 7.0.0
  [
    "カジキ空港",
    "https://cdn.wikimg.net/en/splatoonwiki/images/b/b6/S3_Stage_Marlin_Airport.png"
  ]
]